name: sync-submodules
on:
  repository_dispatch:
    types: [sync-submodules]
  workflow_dispatch:

jobs:
  sync-submodule-notes:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting to sync submodules..."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull latest notes changes
        run: |
          cd notes
          pwd
          git remote -v
          git pull https://${{ secrets.PAT }}@github.com/regexyl/notes.git main
      - run: pwd
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update latest notes contents
