name: sync-submodules
on:
  repository_dispatch:
    types: [sync-submodules]

jobs:
  sync-submodule-notes:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Starting to sync submodules..."
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd ./notes
      - run: git checkout main
      - run: git pull
      - run: cd ..
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update latest notes contents
