name: sync-submodules
on: workflow_dispatch

jobs:
  sync-submodule-notes:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting to sync submodules..."
      - name: Checkout
        uses: actions/checkout@v2
      - run: git submodule update --init --recursive
